### ISSUE TITLE
Como é possivel trocar de janela

### ISSUE THREAD

**Issue by neves8232** [hansalemaos/a_selenium2df#2]
Estou a fazer um projeto onde o site abre um link numa nova janela, preciso que va buscar a informação ao "novo site" como posso gerir as 2 tabs ?

**Comment by hansalemaos** [comment]
é um Pop-Up ou nova aba?

**Comment by neves8232** [comment]
Nova aba

**Comment by neves8232** [comment]
Estou a usar com seleniumbase, mas como o browser abre automaticamente a nova pagina, assumi que a funcao get_df iria focar na nova pagina, mas mesmo chamando ela, fica buscando os dados da pagina anterior

**Comment by neves8232** [comment]
driver.switch_to.window(driver.window_handles[1]) resolveu meu problema, desculpe pelo tempo desperdiçado, muito obrigado e continue com os videos !

**Comment by hansalemaos** [comment]
vlw!! Acho que também dá com a última coluna no dataframe
